version: "3.7"
services:
  user-db:
    restart: always
    image: postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
      - .secret
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - stat_network

  user-stat:
    build:
      dockerfile: Dockerfile.server
      context: .
    links:
      - user-db
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
      - .secret
    volumes:
      - ./app:/app
    networks:
      - stat_network

networks:
  stat_network:
    name: stat_network